### ISSUE TITLE
error 3

### ISSUE THREAD

**Issue by Electrik-rich546456** [emilegill743/grocery-delivery-project#4]
New error.
How do I get this code to respond with `status 200 `
It works with a test interactive python shell 
```
python3.7
Python 3.7.5 (default, Apr 19 2020, 20:18:17) 
[GCC 9.2.1 20191008] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> url = 'https://www.google.co.uk'
>>> page = requests.get(url)
>>> print(page)
<Response [200]>
>>> print(url)
https://www.google.co.uk
>>> 
but with 
>>> url = 'https://groceries.asda.com/api/v3/slot/view'
>>> page = requests.get(url)
>>> print(page)
<Response [405]>

```
Ive added this line  for testing
```
import sys
print(sys.version) 
```
```
3.7.5 (default, Apr 19 2020, 20:18:17) 
[GCC 9.2.1 20191008]
<Response [400]>
{}
Traceback (most recent call last):
  File "/home/user/Documents/Python works/get-grocery-delivery-slots.py", line 47, in <module>
    for slot_day in r.json()['data']['slot_days']:
  File "/usr/lib/python3/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by Electrik-rich546456** [comment]
I fixed it by getting the json data from the site rather than using this code.
